# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-10 15:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemStatementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status',
                 models.CharField(choices=[('S', 'Selected'), ('N', 'Neutral'), ('R', 'Rejected'), ('T', 'Thinking')],
                                  max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='title',
            field=models.CharField(default='', max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammate',
            name='leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statement',
                                    to='mainApp.Organization'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mate',
                                    to='mainApp.Team'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mate',
                                    to='mainApp.TeamMember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ManyToManyField(related_name='team_member', through='mainApp.Teammate', to='mainApp.Team'),
        ),
        migrations.AddField(
            model_name='problemstatementteam',
            name='problem_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ProblemStatement'),
        ),
        migrations.AddField(
            model_name='problemstatementteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem_statement_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ProblemStatementTeam'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Teammate'),
        ),
    ]
