# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0003_auto_20191214_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
