# Generated by Django 3.0 on 2019-12-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0004_auto_20191214_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='dataset_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='organization',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
