# Generated by Django 3.0 on 2019-12-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0005_auto_20191214_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
