# Generated by Django 3.0 on 2019-12-21 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0007_auto_20191215_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemstatement',
            old_name='youtube_link',
            new_name='youtube',
        ),
    ]
