# Generated by Django 3.0 on 2019-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0010_auto_20191221_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatementteam',
            name='status',
            field=models.CharField(
                choices=[('S', 'Selected'), ('N', 'Neutral'), ('R', 'Rejected'), ('I', 'In-Progress')],
                default='Neutral', max_length=30),
        ),
    ]
