# Generated by Django 3.0 on 2019-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0011_auto_20191222_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatementteam',
            name='status',
            field=models.CharField(default='Neutral', max_length=30),
        ),
    ]
