# Generated by Django 3.0 on 2019-12-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0012_auto_20191222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
