# Generated by Django 3.0 on 2019-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0016_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatementteam',
            name='document',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='problemstatementteam',
            name='presentation',
            field=models.URLField(null=True),
        ),
    ]
